steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']
  - name: 'node:18.0'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:18.0'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "${_GOOGLE_APPLICATION_CREDENTIALS}" > /tmp/credentials.json
        gcloud auth activate-service-account --key-file=/tmp/credentials.json
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args:
      - deploy
      - --only=hosting:react-budget-dashboard
timeout: 1200s