steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']
  - name: 'node:18.0'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:18.0'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args:
      - deploy
      - --only=hosting:react-budget-dashboard
timeout: 1200s