steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']
  - name: 'node:18.0'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:18.0'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the service account key from the secret
        gcloud secrets versions access latest --secret=ra-cloud-build-sa-key > /tmp/service-account-key.json

        # Activate the service account using the fetched JSON key
        gcloud auth activate-service-account --key-file=/tmp/service-account-key.json

  - name: 'gcr.io/${_FIREBASE_PROJECT_ID}/firebase'
    args:
      - deploy
      - --only=hosting:react-budget-dashboard
timeout: 1200s